### ISSUE TITLE
4chan placeholder

### ISSUE THREAD

**Issue by bstarling** [Data4Democracy/collect-social#16]
Add 4chan source

[API]( https://github.com/4chan/4chan-API)

**Comment by asabine** [comment]
i wrote a spider for 420chan threads a while back, in case anyone wants to adjust it for other *chans without an API: https://gist.github.com/anonymous/17c1ceab9128714e8c183ee4d0b1ef05

also, 8chan's API endpoints can be found here: https://8ch.net/faq.html#can-i-have-a-list-of-all-api-endpoints-for-getting-raw-data-from-8chan (i also found https://github.com/danjmercurio/eightchanAPI but haven't used it or seen if it works)

**Comment by bstarling** [comment]
Implemented here [smtk](https://github.com/Data4Democracy/smtk)
