### ISSUE TITLE
Add basic twitter functionality

### ISSUE THREAD

**Issue by bstarling** [Data4Democracy/collect-social#2]
### Goal: 
Save tweets/users profiles from twitter to SQLITE db similar to how the below code will save facebook posts/users. Create a new folder in `collect-social/twitter` for the new code.

```
from collect_social.facebook get_posts

app_id = <YOUR APP ID>
app_secret = <YOUR APP SECRET>
connection_string = 'sqlite:///full-path-to-an-existing-database-file.sqlite'

get_posts.run(app_id,app_secret,connection_string,page_ids)
```

### Keep in mind:
* Try to keep api consistent across platforms. I.E. `facebook.get_posts` becomes`twitter.search_tweets` (search) or `twitter.stream_tweets` (streaming)
* Use sane defaults so works with minimal setup/config.
* Consider functionality which can be shared across both platforms be separated from the platform. I.E.`utils/setup_db`

### Resources:
* Introduction to [twitter API](https://github.com/Data4Democracy/assemble/blob/master/tutorials/Intro_Collecting_Tweets.ipynb)
* Notebook streaming tweets from [twitter](https://github.com/Data4Democracy/assemble/blob/master/tutorials/StreamingTweetsFromTwitter.ipynb)

**Comment by georgerichardson** [comment]
I'd like to get started on this.

**Comment by bstarling** [comment]
Sounds good @georgerichardson post here or slack if you come across any interesting choices/questions about the implementation. I recommend checking in a branch early & updating as you work so others can follow the progress & chip in. Thanks for taking this on!

**Comment by gati** [comment]
@georgerichardson I have some code for grabbing search results, timeline tweets, users, and friend/follower in a similar style as the Facebook module if any of that is helpful while you're working through this.

**Comment by bstarling** [comment]
hey @georgerichardson, @metame submitted a start to this issue. I went ahead and merged his additions. If either of you has more twitter code please start a branch and/or chat so we can tag team this one.

**Comment by bstarling** [comment]
Issue is too broad. Replacing with more specific feature issues. Thanks @metame for your contributions so far.
