### ISSUE TITLE
Twitter: User following

### ISSUE THREAD

**Issue by bstarling** [Data4Democracy/collect-social#21]
### Requirements:
* Function should be part of `poll_user`
* Accepts a username, returns a list of people following the user
* Include unit test
* Submit PR to branch v0.1

**Comment by alejandrox1** [comment]
I'll take this one as well

**Comment by bstarling** [comment]
If you are new and want to tag team with @alejandrox1 comment below or DM him on slack. This is a good first issue.

**Comment by lilianhj** [comment]
Hoping to tag team with @alejandrox1 :)

**Comment by bstarling** [comment]
Join #tweepee. We're making lots of changes/planning there!
