### ISSUE TITLE
Twitter: Stream tweets by topic

### ISSUE THREAD

**Issue by bstarling** [Data4Democracy/collect-social#22]
Uses the twitter stream API tweepy streaming [docs](http://tweepy.readthedocs.io/en/v3.5.0/streaming_how_to.html)

### Requirements:
* part of `stream_tweets.py` 
* Setup up a stream listener to follow a list of topics
* Should keep processing through errors on a single tweet.
* Returns FULL tweet object as they come in. Storage of actual tweet will be handled by backed service and out of scope for this piece. Simply return the tweet object is sufficient
* Submit PR to branch v0.1

**Comment by alejandrox1** [comment]
Can I take this one? I'll adapt code from the tutorials

**Comment by metame** [comment]
As you're working on this @alejandrox1 if you can also look at how it works in `discursive` currently

**Comment by bstarling** [comment]
I updated the issue for clarity `storage of actual tweet will be handled by backed service and out of scope for this piece. Simply return the tweet object is sufficient`

**Comment by bstarling** [comment]
This is in progress on `twitter-refactor` branch
