### ISSUE TITLE
Collect from voat.co

### ISSUE THREAD

**Issue by hadoopjax** [Data4Democracy/collect-social#23]
They have an API, ftw. There'll undoubtedly be questions about how to structure the collection but it probably shares 4chan/Reddit/forum characteristics so let's all help out!

**Comment by bartleyn** [comment]
Sorry for the blocking. After digging around the API, here's what I've found: 
* It seems like they may not be issuing keys yet for v1 of the API (you have to request one manually from an admin, but need 10 CCP to send messages), so we may have to rely on the deprecated API [here](https://voat.co/api/help) for immediate access. 
* v1 of the API can be found [here](https://api.voat.co/).

I think the structure is closest to Reddit in form, so maybe we should coordinate between this and #1?

**Comment by bstarling** [comment]
Thanks for looking into this @bartleyn . I am not familiar with voat but _need 10 CCP to send messages_ you need some kind up reputation to message an admin to get a key?

Agree with your observation RE reddit, we might want to put them as part of the same milestone.
